import { StyleSheet } from "react-native";

import { Fonts } from "@/constants/theme";

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  content: { padding: 18, paddingBottom: 30, gap: 18 },
  loading: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  loadingText: { fontFamily: Fonts.sansMedium, fontSize: 15 },
  hero: { borderRadius: 28, padding: 18, overflow: "hidden" },
  heroTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  back: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  readOnly: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  readOnlyText: { color: "#fff", fontFamily: Fonts.sansBold, fontSize: 12 },
  heroTitle: {
    color: "#fff",
    fontFamily: Fonts.sansExtraBold,
    fontSize: 28,
    marginBottom: 8,
  },
  heroSubtitle: {
    color: "rgba(255,255,255,0.9)",
    fontFamily: Fonts.sans,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 18,
  },
  heroMiniRow: { flexDirection: "row", gap: 10 },
  heroMini: {
    flex: 1,
    borderRadius: 18,
    padding: 14,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  heroMiniLabel: {
    color: "rgba(255,255,255,0.76)",
    fontFamily: Fonts.sansMedium,
    fontSize: 12,
    marginBottom: 6,
  },
  heroMiniValue: { color: "#fff", fontFamily: Fonts.sansBold, fontSize: 18 },
  metricsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  metricCard: {
    width: "48.2%",
    minHeight: 146,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
  },
  metricTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  metricIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  metricTitle: { fontFamily: Fonts.sansMedium, fontSize: 12, marginBottom: 8 },
  metricValue: {
    fontFamily: Fonts.sansExtraBold,
    fontSize: 21,
    marginBottom: 8,
  },
  metricMeta: { fontFamily: Fonts.sansMedium, fontSize: 12 },
  health: {
    flex: 1,
    borderRadius: 22,
    padding: 16,
    justifyContent: "space-between",
  },
  healthLabel: {
    color: "rgba(255,255,255,0.8)",
    fontFamily: Fonts.sansMedium,
    fontSize: 12,
  },
  healthValue: { color: "#fff", fontFamily: Fonts.sansBlack, fontSize: 28 },
  healthText: {
    color: "rgba(255,255,255,0.94)",
    fontFamily: Fonts.sans,
    fontSize: 12,
    lineHeight: 18,
  },
  section: { borderWidth: 1, borderRadius: 24, padding: 16 },
  sectionTitle: {
    fontFamily: Fonts.sansExtraBold,
    fontSize: 20,
    marginBottom: 4,
  },
  sectionSub: {
    fontFamily: Fonts.sans,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 12,
  },
  textRtl: {
    textAlign: "right",
  },
  row: { gap: 8, paddingBottom: 10 },
  rowRtl: {
    flexDirection: "row-reverse",
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
  },
  chipText: { fontFamily: Fonts.sansBold, fontSize: 13 },
  compactFilters: { gap: 14 },
  selectorGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  selectorGridRtl: { flexDirection: "row-reverse" },
  selectorCard: {
    minWidth: "31%",
    flex: 1,
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    gap: 8,
  },
  selectorCardRtl: {
    alignItems: "flex-end",
  },
  selectorLabel: {
    fontFamily: Fonts.sansMedium,
    fontSize: 12,
  },
  selectorValueRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  selectorValueRowRtl: {
    flexDirection: "row-reverse",
  },
  selectorValue: {
    flex: 1,
    fontFamily: Fonts.sansBold,
    fontSize: 15,
  },
  resetWrap: { flexDirection: "row", justifyContent: "flex-start" },
  resetWrapRtl: { justifyContent: "flex-end" },
  chartCard: { borderWidth: 1, borderRadius: 20, padding: 14 },
  legend: { flexDirection: "row", gap: 12, marginBottom: 10 },
  legendRtl: { flexDirection: "row-reverse" },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  dot: { width: 10, height: 10, borderRadius: 5 },
  legendText: { fontFamily: Fonts.sansMedium, fontSize: 12 },
  chartArea: { height: 168, position: "relative" },
  grid: { position: "absolute", left: 18, right: 18, borderTopWidth: 1 },
  segment: { position: "absolute", height: 3, borderRadius: 999 },
  point: { position: "absolute", width: 8, height: 8, borderRadius: 4 },
  xLabel: {
    position: "absolute",
    bottom: 0,
    width: 40,
    textAlign: "center",
    fontFamily: Fonts.sansMedium,
    fontSize: 11,
  },
  barRow: { marginBottom: 14 },
  barHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  barHeadRtl: {
    flexDirection: "row-reverse",
  },
  barTitleWrap: { flexDirection: "row", alignItems: "center", gap: 10 },
  barTitleWrapRtl: { flexDirection: "row-reverse" },
  barTitle: { fontFamily: Fonts.sansBold, fontSize: 14 },
  barMeta: { fontFamily: Fonts.sans, fontSize: 12 },
  barAmount: { fontFamily: Fonts.sansBold, fontSize: 14 },
  track: { height: 10, borderRadius: 999, overflow: "hidden" },
  fill: { height: "100%", borderRadius: 999 },
  rhythm: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    height: 170,
  },
  day: { width: "13%", alignItems: "center", justifyContent: "flex-end" },
  dayBars: {
    height: 130,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  dayBar: { width: 12, borderRadius: 999, minHeight: 6 },
  dayLabel: { marginTop: 10, fontFamily: Fonts.sansMedium, fontSize: 11 },
  insightGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  insight: {
    width: "48.2%",
    borderWidth: 1,
    borderRadius: 22,
    padding: 16,
    minHeight: 128,
  },
  insightTitle: {
    fontFamily: Fonts.sansMedium,
    fontSize: 12,
    marginTop: 12,
    marginBottom: 8,
  },
  insightValue: { fontFamily: Fonts.sansBold, fontSize: 16, lineHeight: 22 },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerRowRtl: {
    flexDirection: "row-reverse",
  },
  empty: {
    borderWidth: 1,
    borderRadius: 22,
    padding: 24,
    alignItems: "center",
    gap: 8,
  },
  emptyTitle: { fontFamily: Fonts.sansBold, fontSize: 16, textAlign: "center" },
  emptySub: {
    fontFamily: Fonts.sans,
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
  move: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  moveMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    marginRight: 10,
  },
  moveMainRtl: {
    flexDirection: "row-reverse",
    marginRight: 0,
    marginLeft: 10,
  },
  moveText: { flex: 1 },
  moveTitle: { fontFamily: Fonts.sansBold, fontSize: 15, marginBottom: 2 },
  moveMeta: { fontFamily: Fonts.sans, fontSize: 12, lineHeight: 18 },
  moveAmount: { fontFamily: Fonts.sansExtraBold, fontSize: 15 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(3,7,18,0.42)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 18,
    maxHeight: "70%",
  },
  modalGrabber: {
    width: 48,
    height: 5,
    borderRadius: 999,
    alignSelf: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontFamily: Fonts.sansExtraBold,
    fontSize: 20,
    marginBottom: 12,
  },
  modalOption: {
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 8,
    borderWidth: 1,
  },
  modalOptionText: {
    fontFamily: Fonts.sansBold,
    fontSize: 15,
  },
});
