import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  // HomeHeader styles
  headerContainer: {
    marginHorizontal: 16,
    marginTop: 40,
    marginBottom: 70,         
    borderBottomEndRadius: 24,
    borderBottomStartRadius: 24,
    overflow: 'hidden',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  headerGradient: {
    paddingTop: 40,
    paddingHorizontal: 20,
    paddingBottom: 10,          
    position: 'relative',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  avatarWrapper: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(255,255,255,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.5)',
    marginTop: 50,
    marginLeft: 10,       
    marginRight: 12,   
  },
  headerTextContainer: {
    flex: 1,
  },
  greetingWrapper: {
    width: '100%',
    alignItems: 'center',
  },
  greeting: {
    fontSize: 17,
    fontWeight: '500',
    color: '#fff',
    opacity: 0.9,
    marginBottom: 30,
    paddingRight: 25,       
  },
  menuIcon: {
    position: 'absolute',
    top: -3,
    left: 16,
    opacity: 0.9,
  },
  welcome: {
    fontSize: 15,
    color: '#fff',
    fontWeight: '600',
  },
  name: {
    fontWeight: 'bold',
    color: '#fff',
    fontSize: 24,
  },
  notificationWrapper: {
    position: 'relative',
    top: -38,               
  },
  badge: {
    position: 'absolute',
    top:-4,
    right: -4,
    backgroundColor: '#ef4444',
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
    borderWidth: 1.8,
    borderColor: '#fff',
  },
  badgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  headerBigCircle: {
    position: 'absolute',
    bottom: -50,
    right: -60,              
    width: 100,
    height: 100,
    backgroundColor: '#A866CC',
    borderRadius: 50,
    borderColor: 'rgba(255,255,255,0.25)',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    borderWidth: 2,
  },

  // TotalBalance styles
  balanceContainer: {
    marginHorizontal: 24,
    marginTop: -50,            
    marginBottom: 40,
    borderRadius: 28,
    overflow: 'hidden',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
  },
  balanceGradient: {
    paddingVertical: 32,
    paddingHorizontal: 24,
    position: 'relative',
  },
  balanceContentContainer: {
    alignItems: 'center',
  },
  balanceLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.85)',
    marginBottom: 8,
  },
  balanceAmount: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  changeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 32,
  },
  changeText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#00ff9d',           
    marginLeft: 6,
  },
  incomeExpensesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 20,
  },
  column: {
    alignItems: 'center',
    flex: 1,
  },
  sectionLabel: {
    fontSize: 15,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.8)',
    marginBottom: 6,
  },
  amount: {
    fontSize: 22,
    fontWeight: '700',
  },
  incomeAmount: {
    color: '#00ff9d',
    fontSize: 13,  
    paddingLeft: 20,       
  },
  expensesAmount: {
    color: '#ff4d6d',
    fontSize: 13,
    paddingLeft: -16,        
  },
  balanceBigCircleRight: {
    position: 'absolute',
    top: -60,
    right: -60,
    width: 120,
    height: 120,
    backgroundColor: '#A866CC',
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.25)',
    elevation: 6,
  },
  balanceBigCircleLeft: {
    position: 'absolute',
    bottom: -60,
    left: -60,
    width: 120,
    height: 120,
    backgroundColor: '#304FB5',
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.25)',
    elevation: 6,
  },

  // QuickActions App Styles
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 20,
    paddingHorizontal: 10,
    flexWrap: 'wrap',
  },
  actionsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#566CB2',
    textAlign: 'left',
    marginBottom: 5,
    marginTop: -15,
    marginLeft: 25,
  },
  actionItem: {
    alignItems: 'center',
    width: 90,
    marginBottom: 10,
  },
  actionIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  actionLabel: {
    fontSize: 13,
    color: '#333',
    textAlign: 'center',
    fontWeight: '500',
  },
  customizationLink: {
    fontSize: 13,
    textDecorationLine: 'underline',
    color: '#566CB2',
    marginBottom: 5,
    marginTop: -24,
    textAlign: 'right',
    fontWeight: '500',
    marginRight: 20,
  },

  // Advertisement styles
  adContainer: {
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 40,
    borderRadius: 24,
    overflow: 'hidden',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  adGradient: {
    paddingVertical: 60,         
    paddingHorizontal: 20,
    position: 'relative',
    minHeight: 180,             
  },
  adContent: {
    flex: 1,
    justifyContent: 'center',    
    alignItems: 'center',         
  },
  adText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 1.2,
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  adBigCircleRight: {
    position: 'absolute',
    top: -60,
    right: -60,
    width: 120,
    height: 120,
    backgroundColor: '#A866CC',
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.25)',
    elevation: 6,
  },
  adBigCircleLeft: {
    position: 'absolute',
    bottom: -60,
    left: -60,
    width: 120,
    height: 120,
    backgroundColor: '#304FB5',
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.25)',
    elevation: 6,
  },

  // Customization Styles
  custScreenContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  custHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111',
    marginLeft: 40,
    marginBottom: 40,
    textAlign: 'left',
  },
  custBackButton: {
    position: 'absolute',
    top: 65,
    left: 20,
    zIndex: 10,
  },
  custScrollContainer: {
    flex: 1,
  },
  custScrollContentContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingBottom: 20,
  },
  custItem: {
    width: '31%',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingVertical: 16,
    paddingHorizontal: 6,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  custActiveItem: {
    borderColor: '#566CB2',
    backgroundColor: '#EEF1FF',
  },
  custIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  custTextContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  custItemTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111',
    textAlign: 'center',
    marginBottom: 4,
  },
  custItemSubtitle: {
    fontSize: 11,
    color: '#666',
    textAlign: 'center',
  },
});
